updating to be more universal.

diff --git a/setup_my_env b/setup_my_env
--- a/setup_my_env
+++ b/setup_my_env
@@ -10,7 +10,6 @@ set -e	# better to exit on an error then to let it fuck shit up
 
 # set some variables
 home=$HOME	# gonna use this throughout
-dropbox="Dropbox"	# setting just in case dropbox is different folder, I can change this var
 
 cd "${home}"	# let's go to home directory to do all this work
 
@@ -31,28 +30,25 @@ function checkthencopy ()
 	fi
 }
 
-# Check if there is a dropbox folder (because I keep my_env files in dropbox) but on servers and other systems where
-# i'm not using dropbox, I need to use just the local user folder without dropbox in the mix
-if [ -d "${home}/${dropbox}/" ]; then
-	myenvrootdir="${home}/${dropbox}/"
-else
-	myenvrootdir="${home}/"
-fi
+myenvrootdir="${home}/"
 
 # run checks and copy if needed for backup
 checkthencopy .bashrc
 checkthencopy .vim
 checkthencopy .vimrc
+checkthencopy .tmux.conf
 
 # remove originals
 rm ~/.bashrc && { echo "Original .bashrc removed"; } || { echo "Error removing original .bashrc"; }
 rm -r ~/.vim && { echo "Original .vim removed"; } || { echo "Error removing original .vim"; }
 rm ~/.vimrc && { echo "Original .vimrc removed"; } || { echo "Error removing original .vimrc"; }
+rm ~/.tmux.conf && { echo "Original .tmux.conf removed"; } || { echo "Error removing original .tmux.conf"; }
 
 # symlink to my_env files
 ln -nfs "${myenvrootdir}my_env/bash/bashrc" .bashrc && { echo "Symlink to .bashrc in my_env/bash successful"; } || { echo "Symlink to my_env/.bashrc not made"; }  
 ln -nfs "${myenvrootdir}my_env/vim/" .vim && { echo "Symlink to .vim in my_env/ successful"; } || { echo "Symlink to my_env/.vim not made"; }
 ln -nfs "${myenvrootdir}my_env/vim/vimrc" .vimrc && { echo "Symlink to .vimrc in my_env/ successful"; } || { echo "Symlink to my_env/.vimrc not made"; }
+ln -nfs "${myenvrootdir}my_env/tmux/tmux.conf" .tmux.conf && { echo "Symlink to .tmux.conf in my_env/ successful"; } || { echo "Symlink to my_env/.tmux not made"; }
 
 printf "\n\n"
 echo "========================================="
